---
- name: install docker
  apt:
    name='docker'
    state=latest

- name: service docker
  service:
    name=docker
    state=started
    enabled=yes

- name: Ensure docker-compose is installed and available
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.26.0-rc3/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }} 
    dest: /usr/bin/docker-compose
    mode: 'u+x,g+x'